name: Build and push image

on:
  workflow_call:
    inputs:
      push:
        description: "Flag to determine if the image should be pushed to the registry"
        default: true
        type: boolean
      image-name:
        description: "The name of the image to be built"
        type: string
        required: true
      registry-url:
        description: "The URL of the container registry"
        type: string
        required: true
      tag:
        description: "The tag of the image to be built"
        type: string
        required: true
    outputs:
      image:
        description: "The output representing the built image"
        value: ${{ jobs.build-and-push-image.outputs.image }}
    secrets:
      registry-username:
        description: "The username for the container registry"
        required: true
      registry-password:
        description: "The password for the container registry"
        required: true
      github-token:
        description: "Github token to be able to build inside the container"
        required: true

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set image
        id: set-image
        run: echo "image=${{ inputs.image-name }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.set-image.outputs.image }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.github-token }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    outputs:
      image: ${{ steps.set-image.outputs.image }}
