name: Test Pull Request

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      rhacs-central-endpoint:
        description: "The endpoint URL of the RHACS Central server for authentication."
        type: string
        required: true
    secrets:
      github-user:
        description: "Github username for the container registry"
        required: true
      github-token:
        description: "Github token to be able to build inside the container"
        required: true
      registry-username:
        description: "The username for the container registry"
        required: true
      registry-password:
        description: "The password for the container registry"
        required: true

jobs:
  build-and-test:
    uses: ./.github/workflows/dotnet-build-and-test.yml
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
    secrets:
      github-user: ${{ secrets.github-user }}
      github-token: ${{ secrets.github-token }}

  next-version:
    needs: "build-and-test"
    uses: ./.github/workflows/next_version.yaml

  build-and-push-image:
    needs: "next-version"
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      registry-url: "quay.io"
      image-name: "quay.io/agronod/ghcr.io/${{ github.repository }}"
      tag: ${{ needs.next-version.outputs.tag }}
    secrets:
      registry-username: ${{ secrets.registry-username }}
      registry-password: ${{ secrets.registry-password }}
      github-token: ${{ secrets.github-token }}

  scan-and-check-image:
    needs: "build-and-push-image"
    uses: ./.github/workflows/scan-and-check-image.yml
    permissions:
      id-token: write
    with:
      rhacs-central-endpoint: ${{ inputs.rhacs-central-endpoint }}
      image: ${{ needs.build-and-push-image.outputs.image }}
