name: Next version
on:
  workflow_call:
    inputs:
      release_branches:
        default: "master,main"
        type: string
      pre_release_branches:
        default: "develop,release"
        type: string
    outputs:
      version:
        description: Next version
        value: ${{ jobs.next-version.outputs.version }}
      tag:
        description: Next tag
        value: ${{ jobs.next-version.outputs.tag }}
    secrets:
      github-token:
        description: "Github token to be able to build inside the container"
        required: true

jobs:
  next-version:
    name: Get Next Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for pull request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          submodules: "true"
          token: ${{ secrets.github-token }}

      - name: Set environment variables
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            GITHUB_SHA="${{ github.event.number }}-$(git rev-parse --short $GITHUB_SHA)"
            echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
          fi

      - name: Identify new semver version
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          fetch_all_tags: true
          commit_sha: ${{ env.GITHUB_SHA }}
          release_branches: ${{ inputs.release_branches }}
          pre_release_branches: ${{ inputs.pre_release_branches }}
          github_token: ${{ secrets.github-token }}

      - name: Show tag and version
        run: |
          echo "Tag: ${{ steps.tag_version.outputs.new_tag }}"
          echo "Version: ${{ steps.tag_version.outputs.new_version }}"

    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      version: ${{ steps.tag_version.outputs.new_version }}
