name: Next version
on:
  workflow_call:
    outputs:
      version:
        description: Next version
        value: ${{ jobs.next-version.outputs.version }}
      tag:
        description: Next tag
        value: ${{ jobs.next-version.outputs.tag }}
    secrets:
      github-token:
        description: "Github token to be able to build inside the container"
        required: true

jobs:
  next-version:
    name: Get Next Version
    runs-on: ubuntu-latest

    steps:
      - name: Identify new semver version
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.github-token }}

      - name: Set outputs for tag and version
        id: set_tag_version
        run: |
          echo "NEW_TAG=${{ steps.tag_version.outputs.new_tag }}"
          echo "NEW_VERSION=${{ steps.tag_version.outputs.new_version }}"
          echo "::set-output name=tag::${{ steps.tag_version.outputs.new_tag }}"
          echo "::set-output name=version::${{ steps.tag_version.outputs.new_version }}"

      - name: Modify tag and version for pull request
        if: github.event_name == 'pull_request'
        run: |
          NEW_TAG="${{ steps.tag_version.outputs.new_tag }}-${{ github.event.number }}-$(git rev-parse --short $GITHUB_SHA)"
          NEW_VERSION="${{ steps.tag_version.outputs.new_version }}-${{ github.event.number }}-$(git rev-parse --short $GITHUB_SHA)"
          echo "::set-output name=tag::${NEW_TAG}"
          echo "::set-output name=version::${NEW_VERSION}"

      - name: Show tag
        run: |
          echo "${{ steps.set_tag_version.outputs.tag }}"

      - name: Show version
        run: |
          echo "${{ steps.set_tag_version.outputs.version }}"

    outputs:
      tag: ${{ steps.set_tag_version.outputs.tag }}
      version: ${{ steps.set_tag_version.outputs.version }}
