name: Promote Agronod application

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      application-name:
        required: true
        type: string
      application-folder:
        required: true
        type: string
      image-tag-parameter:
        default: "image.tag"
        type: string
      platform:
        description: "(Deprecated) The platform to deploy to."
        default: "elastisys"
        type: string
      environment:
        description: "Override environment (e.g., dev, test, staging, production). If not provided, will be calculated from branch."
        required: false
        type: string
    secrets:
      github-token:
        required: true

jobs:
  promote:
    name: Promote
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: agronod/application-gitops
          branch: main
          token: ${{ secrets.github-token }}

      - name: Set environment info
        id: set-env
        run: |
          # Determine environment (from input or branch)
          if [ -n "${{ inputs.environment }}" ]; then
            ENV="${{ inputs.environment }}"
            echo "env=${ENV}" >> $GITHUB_OUTPUT
          else
            case "${REF}" in
              refs/heads/develop)
                ENV="dev"
                ;;
              refs/heads/release)
                ENV="test"
                ;;
              refs/heads/main)
                ENV="staging"
                ;;
              *)
                echo "Unknown branch. Skipping."
                exit 1
                ;;
            esac
            echo "env=${ENV}" >> $GITHUB_OUTPUT
          fi

          # Derive cluster from environment
          case "${ENV}" in
            dev|test)
              echo "cluster=dev" >> $GITHUB_OUTPUT
              ;;
            staging|production|prod)
              echo "cluster=prod" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Unknown environment: ${ENV}. Cannot determine cluster."
              exit 1
              ;;
          esac
        env:
          REF: ${{ github.ref }}

      - name: Promote to OCP
        if: ${{ steps.set-env.outputs.env != '' && inputs.platform == 'ocp' }}
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ${{ steps.set-env.outputs.cluster }}-${{ inputs.platform }}/${{ steps.set-env.outputs.env }}/${{ inputs.application-folder }}/${{ inputs.application-name }}.yaml
          propertyPath: "$.spec.source.helm.parameters[?(@.name=='${{ inputs.image-tag-parameter }}')].value"
          value: ${{ inputs.tag }}
          commitChange: false

      - name: Promote to Elastisys
        if: ${{ steps.set-env.outputs.env != '' && inputs.platform != 'ocp' }}
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ${{ steps.set-env.outputs.cluster }}-elastisys/${{ steps.set-env.outputs.env }}/${{ inputs.application-folder }}/${{ inputs.application-name }}.yaml
          propertyPath: "$.spec.source.helm.parameters[?(@.name=='${{ inputs.image-tag-parameter }}')].value"
          value: ${{ inputs.tag }}
          commitChange: false

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump ${{ inputs.application-name }}:${{ inputs.tag }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: agronod/application-gitops
          github_token: ${{ secrets.github-token }}
          branch: main
