name: Python CI

on:
  workflow_call:
    inputs:
      python-version:
        default: "3.10"
        type: string
      rhacs-central-endpoint:
        description: "The endpoint URL of the RHACS Central server for authentication."
        type: string
        required: true
      test:
        default: true
        type: boolean
      check-image:
        default: true
        type: boolean
      dockerfile:
        description: "The name of the Dockerfile to be used"
        type: string
        required: false
        default: "Dockerfile"
      image-name:
        description: "The name of the image to be built"
        type: string
        required: false
    secrets:
      github-user:
        description: "Github username for the container registry"
        required: true
      github-token:
        description: "Github token to be able to build inside the container"
        required: true
      registry-username:
        description: "The username for the container registry"
        required: true
      registry-password:
        description: "The password for the container registry"
        required: true
      container-build-args:
        description: "Container build args"
        required: false

jobs:
  test:
    uses: ./.github/workflows/python-test.yml
    with:
      python-version: ${{ inputs.python-version }}
      enabled: ${{ inputs.test }}
    secrets:
      github-user: ${{ secrets.github-user }}
      github-token: ${{ secrets.github-token }}

  next-version:
    needs: "test"
    uses: ./.github/workflows/next-version.yaml
    with:
      is-pull-request: true
    secrets:
      github-token: ${{ secrets.github-token }}

  build-and-push-image:
    needs: "next-version"
    uses: ./.github/workflows/build-and-push-image-v2.yml
    with:
      registry-url: "quay.io"
      image-name: ${{ inputs.image-name }}
      tag: ${{ needs.next-version.outputs.version }}
      dockerfile: ${{ inputs.dockerfile }}
    secrets:
      registry-username: ${{ secrets.registry-username }}
      registry-password: ${{ secrets.registry-password }}
      container-build-args: ${{ secrets.container-build-args }}

  scan-and-check-image:
    needs: "build-and-push-image"
    uses: ./.github/workflows/scan-and-check-image.yml
    permissions:
      id-token: write
    with:
      rhacs-central-endpoint: ${{ inputs.rhacs-central-endpoint }}
      check-image: ${{ inputs.check-image }}
      image: ${{ needs.build-and-push-image.outputs.image }}
