name: Test python application

on:
  workflow_call:
    inputs:
      python-version:
        default: '3.10'
        type: string
    secrets:
      github-token:
        required: true

jobs:
  python-install-and-test:
    name: python install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}
      - name: Set env parameters
        run: |
          echo "GITHUB_TOKEN=${{ secrets.github-token }}" >> "$GITHUB_ENV"
          echo "GITHUB_USER=${{ secrets.github-token }}" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
