name: Scanning and check image

on:
  workflow_call:
    inputs:
      image:
        description: "The URL of the container image to be scanned and checked."
        required: true
        type: string
      rhacs-central-endpoint:
        description: "The endpoint URL of the RHACS Central server for authentication."
        type: string
        required: false
      check-image:
        description: "Whether to scan the image"
        default: true
        type: boolean
      enforce-scanning:
        description: "Whether to enforce vulnerabilities as failures"
        default: true
        type: boolean
    secrets:
      registry-username:
        description: "The username for the container registry"
        required: true
      registry-password:
        description: "The password for the container registry"
        required: true
      github-token:
        description: "Github token to be able to checkout trivyignore repo"
        required: true
jobs:
  scan-and-check-image:
    name: Scanning and check image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "agronod/trivyignore"
          token: '${{ secrets.github-token }}'

      - name: Check for repo-specific .trivyignore.yaml
        run: |
          REPO_NAME=$(basename "${{ github.repository }}")
          IGNORE_FILE="$REPO_NAME/.trivyignore.yaml"

          if [ -f "$IGNORE_FILE" ]; then
            echo "TRIVY_IGNOREFILE=$IGNORE_FILE" >> $GITHUB_ENV
          fi

      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.check-image }}
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ inputs.image }}'
          format: 'table'
          exit-code: ${{ inputs.enforce && '1' || '0' }}
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ secrets.registry-username }}
          TRIVY_PASSWORD: ${{ secrets.registry-password }}