name: Tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Tag the Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}
